version: '3.8'

services:
  postgres-gestion:
    image: postgis/postgis:15-3.3
    container_name: postgres-gestion
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - sanos-network
    volumes:
      - pg_data_gestion:/var/lib/postgresql/data

  ms-mascotas:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sanos-ms-mascotas
    ports:
      - "${PORT}:${PORT}"
    environment:
      DB_HOST: postgres-gestion
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      PORT: ${PORT}
    depends_on:
      - postgres-gestion
    networks:
      - sanos-network

networks:
  sanos-network:
    external: true

volumes:
  pg_data_gestion: